name: pyramid_lint_test
description: Test for pyramid_lint
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ">=7.0.0 <8.0.0"
  analyzer_plugin: ">=0.12.0 <0.14.0"
  custom_lint: ">=0.7.0 <0.8.0"
  custom_lint_core: ">=0.7.0 <0.8.0"
  flutter_test:
    sdk: flutter
  path: ^1.8.3
  pub_semver: ^2.1.4
  pubspec_parse: ^1.4.0
  pyramid_lint:
    path: ../pyramid_lint
  test: ^1.25.9
