name: pyramid_lint_test
description: Test for pyramid_lint
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^6.6.0
  analyzer_plugin: ^0.11.3
  custom_lint: ^0.6.5
  custom_lint_core: ^0.6.5
  flutter_test:
    sdk: flutter
  path: ^1.8.3
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  pyramid_lint:
    path: ../pyramid_lint
  test: ^1.24.9
